---

- name: Install & configure Hashicorp Consul cluster
  hosts: consul
  become: yes
  gather_facts: yes

  roles:
    - { role: ansible-role-consul-remove, tags: remove }
    - { role: ansible-role-consul-install, tags: install }
    - { role: ansible-role-consul-start, tags: start }
    - { role: ansible-role-consul-stop, tags: stop }


