---
# defaults file for ansible-role-consul-install

consul_src: "https://releases.hashicorp.com/consul/1.2.0/consul_1.2.0_linux_amd64.zip"
consul_chksum: "sha256:85d84ea3f6c68d52549a29b00fd0035f72c2eabff672ae46ca643cb407ef94b4"
consul_dependencies:
  - unzip
consul_bin_path: "/usr/bin"
consul_path: "/var/lib/consul"
consul_conf: "/etc/consul/consul_agent.hcl"
consul_datacenter: "dc1"
consul_base_ip: "10.1.42."
consul_user: "consul"
consul_uid: "8501"
consul_group: "consul"
consul_gid: "8501"
consul_service: "consul"

