---
# tasks file for ansible-role-vault-init

- name: Start vault systemd service
  systemd:
    name: "{{ vault_service }}"
    state: started

# To be run on only one vault host for each inventory source
- name: Initialise vault
  uri:
    url: "https://{{ vault_addr }}:{{ vault_port }}/v1/sys/init"
#    client_cert: "{{ vault_certfile }}"
    validate_certs: no
    method: PUT
    body: "{{ lookup('file','init_params.json') }}"
    body_format: json
    return_content: yes
    status_code: 200
  loop: "{{ inv_vault | dict2items }}"
  when:
    - inventory_dir | basename == item['key']
    - inventory_hostname == item['value'][0]
  become: no
  # TODO: Remove comment
  #no_log: yes
  register: vault_init

- name: Create keys directories
  file:
    path: "{{ vault_keysdir | default('~') }}/{{ item['key'] }}"
    state: directory
    mode: 0700
  loop: "{{ inv_vault | dict2items }}"
  become: no
  delegate_to: localhost
  run_once: yes
  
- name: Save keys locally
  copy:
    content: "{{ hostvars[item['value'][0]]['vault_init']['results'][0]['json'] | to_nice_json(indent=2) }}"
    dest: "{{ vault_keysdir | default('~') }}/{{ item['key'] }}/{{ vault_keysfile }}"
    mode: 0600
  loop: "{{ inv_vault | dict2items }}"
  become: no
  # TODO: Remove comment
  #no_log: yes
  delegate_to: localhost
  run_once: yes

