---
# tasks file for ansible-role-vault-approle

- name: Retrieve keys locally
  set_fact:
    vault_keys: "{{ vault_keys | default({}) | combine( { item['key']: lookup('file', vault_keysdir | default('~') + '/' +  item['key'] + '/' + vault_keysfile) | from_json } ) }}"
  loop: "{{ inv_vault | dict2items }}"
  become: no
  no_log: yes
  delegate_to: localhost
  run_once: yes

- name: Enable approle auth method
  uri:
    url: "https://{{ vault_addr }}:{{ vault_port }}/v1/sys/auth/approle"
    validate_certs: no
    method: POST
    headers:
      X-Vault-Token: "{{ vault_keys[inventory_dir | basename]['root_token'] }}"
    body: "{{ lookup('template', 'approle_params.json.j2') }}"
    body_format: json
    return_content: yes
    status_code: 204
  loop: "{{ inv_vault | dict2items }}"
  when:
    - inventory_dir | basename == item['key']
    - inventory_hostname == item['value'][0]
  become: no
  register: result
  # Don't fail if "path is already in use" message appears
  failed_when:
    - result['status'] not in [204]
    - "'path is already in use' not in result['content']"

- name: Create {{ approle_name }} policy
  uri:
    url: "https://{{ vault_addr }}:{{ vault_port }}/v1/sys/policy/{{ approle_name }}"
    validate_certs: no
    method: PUT
    headers:
      X-Vault-Token: "{{ vault_keys[inventory_dir | basename]['root_token'] }}"
    # This simple line took me 2 days to get working, I felt that needed mentioning!
    body: { "policy": "{{ lookup('template','policy-approle.hcl.j2') }}" }
    body_format: json
    return_content: yes
    status_code: 204
  loop: "{{ inv_vault | dict2items }}"
  when:
    - inventory_dir | basename == item['key']
    - inventory_hostname == item['value'][0]
  become: no

- name: Create {{ approle_name }} role
  uri:
    url: "https://{{ vault_addr }}:{{ vault_port }}/v1/auth/approle/role/{{ approle_name }}"
    validate_certs: no
    method: POST
    headers:
      X-Vault-Token: "{{ vault_keys[inventory_dir | basename]['root_token'] }}"
    body: "{{ lookup('template','role_approle.json.j2') }}"
    body_format: json
    return_content: yes
    status_code: 204
  loop: "{{ inv_vault | dict2items }}"
  when:
    - inventory_dir | basename == item['key']
    - inventory_hostname == item['value'][0]
  become: no

