---
# handlers file for ansible-role-haproxy-install

- name: restart consul
  systemd:
    name: "{{ consul_service }}"
    daemon_reload: yes
    state: reloaded
  listen: "restart consul"

- name: Restart and enable HAProxy & Keepalived services
  systemd:
    name: "{{ item }}"
    daemon_reload: yes
    state: restarted
    enabled: yes
  loop:
    - "haproxy"
    - "keepalived"
  listen: "restart haproxy"

