---
# tasks file for ansible-role-vault-unseal

- name: Start vault systemd service
  systemd:
    name: "{{ vault_service }}"
    state: started

- name: Retrieve keys locally
  set_fact:
    vault_keys: "{{ vault_keys | default({}) | combine( { item['key']: lookup('file', vault_keysdir | default('~') + '/' +  item['key'] + '/' + vault_keysfile) | from_json } ) }}"
  loop: "{{ inv_vault | dict2items }}"
  become: no
  # TODO: Remove comment
  #no_log: yes
  delegate_to: localhost
  run_once: yes

- name: Loop unseal tasks for each environment
  include_tasks: unseal.yml
  #loop: "{{ hostvars['localhost']['inv_vault'] | dict2items }}"
  # Using with_dict as include_tasks doesn't accept the loop equivalent!
  with_dict: "{{ inv_vault }}"
  loop_control:
    loop_var: inv_loop
  become: no

