- name: Unseal vault
  uri:
    #url: "https://{{ item[0] }}:{{ vault_port }}/v1/sys/unseal"
    url: "https://{{ vault_addr }}:{{ vault_port }}/v1/sys/unseal"
    validate_certs: no
    method: PUT
    body: "{ 'key':'{{ item }}' }"
    body_format: json
    return_content: yes
    status_code: 200
  # Pick threshold number of random keys from keys list
  loop: "{{ (vault_keys[inv_loop['key']]['keys'] | shuffle) [:vault_key_threshold] }}"
  when:
    - inventory_dir | basename == inv_loop['key']
    - inventory_hostname in inv_loop['value']
  become: no
  # TODO: Remove comment
  #no_log: yes

