---

- name: Install & configure Hashicorp Consul cluster
  hosts: consul:vault:haproxy
  become: yes
  gather_facts: yes

  roles:

    - name: Remove consul agents
      role: ansible-role-consul-remove
      tags:
        - 'never'
        - 'remove'

    - name: Install consul agents
      role: ansible-role-consul-install
      tags:
        - 'install'

    - name: Start consul agents
      role: ansible-role-consul-start
      tags:
        - 'never'
        - 'start'

    - name: Stop consul agents
      role: ansible-role-consul-stop
      tags:
        - 'never'
        - 'stop'

- name: Consul backup management
  hosts: consul
  become: no
  gather_facts: no

  roles:

    - name: Backup consul server data
      role: ansible-role-consul-backup
      tags:
        - 'never'
        - 'backup'

