---

- name: Install & configure Hashicorp Vault
  hosts: vault
  become: yes
  gather_facts: yes

  roles:

    - name: Remove vault
      role: ansible-role-vault-remove
      tags:
        - 'never'
        - 'remove'

    - name: Enable EPEL repo
      role: ansible-role-repo-epel
      when:
        - ansible_os_family == 'RedHat'
      tags:
        - 'epel'

    - name: Install vault
      role: ansible-role-vault-install
      tags:
        - 'install'

    - name: Start vault
      role: ansible-role-vault-start
      tags:
        - 'never'
        - 'start'

    - name: Initialise vault
      role: ansible-role-vault-init
      tags:
        - 'init'

    - name: Unseal vault
      role: ansible-role-vault-unseal
      tags:
        - 'unseal'

    - name: Configure vault
      role: ansible-role-vault-configure
      tags:
        - 'configure'

    - name: Enable approle in vault
      role: ansible-role-vault-approle
      tags:
        - 'approle'

    - name: Enable SSH key signing in vault
      role: ansible-role-vault-sshkeysign
      tags:
        - 'sshkeysign'

    - name: Stop vault
      role: ansible-role-vault-stop
      tags:
        - 'never'
        - 'stop'

